import Test.Hspec
import Repeats

main = hspec $ do
    describe "twice" $ do
        it "should tell if a letter is in here twice" $ do
            twice "parody"  `shouldBe` False
            twice "hello" `shouldBe` True
            twice "banana" `shouldBe` True
    describe "thrice" $ do
        it "should tell if a letter is in here thrice" $ do
            thrice "parody"  `shouldBe` False
            thrice "hello" `shouldBe` False
            twice "banana" `shouldBe` True

    describe "twice and thrice" $ do
        it "should count strings with letter twice and thrice" $ do
            let small = ["abcdef"
                        ,"bababc"
                        ,"abbcde"
                        ,"abcccd"
                        ,"aabcdd"
                        ,"abcdee"
                        ,"ababab"]

            twiceAndThrice small  `shouldBe` (4,3)
            twiceAndThrice large  `shouldBe` (247,22)
            247 * 22 `shouldBe` 5434

    describe "differ by one letter" $ do
        it "should tell if 2 strings differ by one letter only" $ do
            differ "hello" "hello" `shouldBe` False
            differ "hell" "help" `shouldBe` True
            differ "hello" "help" `shouldBe` False
            differ "hall" "help" `shouldBe` False

    describe "common letters" $ do
        it "should tell which letters are common to 2 words" $ do
            common "hall" "help"  `shouldBe` "hl"

    describe "similar" $ do
        it "should tell which 2 strings are similar" $ do
            similar small  `shouldBe` "fgij"
            similar large  `shouldBe` "agimdjvlhedpsyoqfzuknpjwt"

small = ["abcde"
        ,"fghij"
        ,"klmno"
        ,"pqrst"
        ,"fguij"
        ,"axcye"
        ,"wvxyz"]

large = ["ayitmcjvlhedbsyoqfzukjpxwt"
        ,"agirmcjvlheybsyogfzuknpxxt"
        ,"wgirmcjvlvedbsyoqfzujnpxwt"
        ,"agizmcjvlhedbsyoqfzuenlxwt"
        ,"aryrmcjvlheebsyoqfzuknpxwt"
        ,"agirmcjelhedbsyoqfzukosxwt"
        ,"azirmcjvlhedbsooqfzuknpxvt"
        ,"agirmcjvffedbsyoqfzudnpxwt"
        ,"agilmcjvlhedbsyrqfzuknpxrt"
        ,"agirmcjvlhndbsyoofzukcpxwt"
        ,"awirmcjvlhedbsyoqfzuknpxlz"
        ,"aghrmcjmlhewbsyoqfzuknpxwt"
        ,"apirmcjvlmedbsyoqfzcknpxwt"
        ,"jgiricjvlhedbsyrqfzuknpxwt"
        ,"abirmcjvlbedbsyoqfzuknpxwo"
        ,"agirmcjvlhedbsyojfzuknpgkt"
        ,"agicmclvlhedbmyoqfzuknpxwt"
        ,"aslrzcjvlhedbsyoqfzuknpxwt"
        ,"agiqmcjvlhedbsymqfzurnpxwt"
        ,"agirmcjvlwedbsyoqfzuknfxmt"
        ,"agiumcjvlhedbsyoqfzuknpbyt"
        ,"xgirxcjvlwedbsyoqfzuknpxwt"
        ,"bgtrvcjvlhedbsyoqfzuknpxwt"
        ,"afirmcjvlpedbsyoqvzuknpxwt"
        ,"agirmcjjvhedbsyoqfzukmpxwt"
        ,"ggirmcjvlhedbsyoqfzukypxvt"
        ,"agirmdjulhekbsyoqfzuknpxwt"
        ,"agirmcjqlhedbsyoqfztknixwt"
        ,"agirmcjvjhedbsyomfduknpxwt"
        ,"agirmcjvlhedbgyoqfzuknpxtq"
        ,"agirmvjvlhbdbsyfqfzuknpxwt"
        ,"agirmcjvlhedbsyatfzbknpxwt"
        ,"agirmcjvlrlybsyoqfzuknpxwt"
        ,"agirmajvlhedbsqovfzuknpxwt"
        ,"abinmcrvlhedbsyoqfzuknpxwt"
        ,"agnrmcjvlhedbsyurfzuknpxwt"
        ,"agirmpjvlhedbsyoqezuknpxct"
        ,"agirmxjvlhedbsgoqjzuknpxwt"
        ,"agirmcjvlhehbstoqfzuknpxht"
        ,"qgirmcjvlhepcsyoqfzuknpxwt"
        ,"tgirmcjvlhkdbsyoqszuknpxwt"
        ,"agirmcjvdhedbscoqftuknpxwt"
        ,"agbrmcjvlhedbsyoqfzukqpxwj"
        ,"agurmcjvlhedbsyaqfzuknpxmt"
        ,"agirmcjvohudbsyoqfmuknpxwt"
        ,"agirmcjvlhekbsyoqfbuktpxwt"
        ,"agirmcjvlhedhsyoqfzugnnxwt"
        ,"agirmcjvlhedbsyjqyzuknpxft"
        ,"agirmcjvlhedbsymufznknpxwt"
        ,"agirmcjhlheubsyoqfzuknpxmt"
        ,"agirmcjvlhwdbsywqfzwknpxwt"
        ,"agirmcjvljedbsgqqfzuknpxwt"
        ,"aglrmcjelhedbsyoqfzuknpxkt"
        ,"agxrmcjvlhxdbsyoqfquknpxwt"
        ,"agirmcjvnhedbsyoqfzuenfxwt"
        ,"agirmcjvlhedbsyoqfzatnqxwt"
        ,"agirmcvvlhedbsboqfzuknuxwt"
        ,"agirncjvlhezbsyoqfzulnpxwt"
        ,"agiamcjvdiedbsyoqfzuknpxwt"
        ,"agirmcjvwhedbskoqfzhknpxwt"
        ,"agiwmcjflhedbsyoqfzulnpxwt"
        ,"agirmcjvlhedboyoqfzuknpjwl"
        ,"agivmcjslhedbsyoqfzdknpxwt"
  ,"agirmcjvlcedbsyoqfzukepxyt"
  ,"akirmcjvlhjdbssoqfzuknpxwt"
  ,"agvrmcjvldedmsyoqfzuknpxwt"
  ,"agirecjvlhidbsyoqfzukbpxwt"
  ,"abirmcjvlhjdbsyoqfkuknpxwt"
  ,"agirmcjelhedbfyoqfzuknpxwj"
  ,"agirmcjvlhedbbyoqrzukwpxwt"
  ,"akirmcjvlhedbsyoyfzuknplwt"
  ,"agirmcjvlhedbsydsfzuknpxwq"
  ,"agirrcjvlhedbsyoqazuknpmwt"
  ,"aeirmcjvlhedbsyoqfvuknpwwt"
  ,"akirmcjvlhedbsyoqpzudnpxwt"
  ,"agijmcjvlhedbsyuqfzunnpxwt"
  ,"agirmcjilhedasyoqizuknpxwt"
  ,"agirmczvlhzdbsyoqfzuknpxwx"
  ,"agirmcjvlhehbsyoifzuknpxwo"
  ,"agirwcjvlhedbsyoqfzuenpxst"
  ,"agirmcjvlhedbsyoquzuknhxft"
  ,"agirmcqvlkedbsyoqfzrknpxwt"
  ,"agirmcqvlhenbsyoqfzuknpuwt"
  ,"agirmcjvleedbsyoqfzhhnpxwt"
  ,"agirmcjvlhembsyrqfauknpxwt"
  ,"agirmcjvlhedbssoqflcknpxwt"
  ,"aqirmcjvlnedbsyoqfzuknpxpt"
  ,"agirmcjqlhedbxpoqfzuknpxwt"
  ,"fgirmcjvlhedbsyoqfzukqpqwt"
  ,"aggrmcjvlhpdbsyoqfzuknpxjt"
  ,"agirmwjvlhedbsywqfzuknpzwt"
  ,"agirmcailhembsyoqfzuknpxwt"
  ,"aglrmcjvlhxdbsyoqfzuknpxet"
  ,"xgirmcjvlhzdbsyoqfzukrpxwt"
  ,"agvrmcjvuhedbsyoqfzuknpxgt"
  ,"agikmcjvlhecbsyoqfzuknpxwr"
  ,"agyrmcjvlhezbsyoqfouknpxwt"
  ,"agirmcjvfhjdbsyokfzuknpxwt"
  ,"agkrmjjvlhedtsyoqfzuknpxwt"
  ,"agirmgjvlhedbiyoqfzuknpxwv"
  ,"wcirmcjvlhedbsyoqfzuknpxwo"
  ,"aairmcjvlhedbstoqfguknpxwt"
  ,"hgirmcjvlhedwfyoqfzuknpxwt"
  ,"agirmcjvmhfdbmyoqfzuknpxwt"
  ,"agirmcjvlhvdbsioqfzuanpxwt"
  ,"agrrmcjvgsedbsyoqfzuknpxwt"
  ,"agirmcjvlqetbsysqfzuknpxwt"
  ,"agirccjvlhedbsyoqfzuknkcwt"
  ,"agirmqjvlhedbsdoqfzkknpxwt"
  ,"agirmcjvlheobsyopfzuknpxwg"
  ,"agirmcjolhedbsyofpzuknpxwt"
  ,"agirmcjnlhedbsyoqkzukfpxwt"
  ,"agiumcjvlheabsyoqfzuknpxbt"
  ,"agipmcjvlhedbsyoqfzukupxwz"
  ,"atirmcrvlhedbsyoqfnuknpxwt"
  ,"agirmcjvnhedfkyoqfzuknpxwt"
  ,"agirmrjvlhedboyoqfzvknpxwt"
  ,"abhrmcjvlhedbtyoqfzuknpxwt"
  ,"cbirmcjvlhedbfyoqfzuknpxwt"
  ,"agirmcjvlhedbsyoqfmwknjxwt"
  ,"ahirmcjvlhedbsloqfzuknpfwt"
  ,"agarmjjvlhedbsyoqfzyknpxwt"
  ,"ajirmcjvlhevjsyoqfzuknpxwt"
  ,"agirmcjvlhpdbstoqfzuknpewt"
  ,"agirmcsvlhedbsyoqfbupnpxwt"
  ,"agirmcjvlhexbsyodfzukqpxwt"
  ,"auiymcjblhedbsyoqfzuknpxwt"
  ,"azirmcjvchedbsyoqfziknpxwt"
  ,"aeirmcjvlhedvsyoqfzuonpxwt"
  ,"agirmcjvlhedbfyoqfbukjpxwt"
  ,"ygirmcjvlhidbsyoqfzukncxwt"
  ,"agirmxpvlhedbsyoqffuknpxwt"
  ,"ztirmcjvlhedosyoqfzuknpxwt"
  ,"agirmcjvlhepbsyoqfzuenppwt"
  ,"agirmcjvshedbsyoqnzaknpxwt"
  ,"awirmcjvlhydbsyoqfzuknoxwt"
  ,"ucirmcjvlhedbsyoqfjuknpxwt"
  ,"agirmwjvlhkbbsyoqfzuknpxwt"
  ,"agirmcjvldedbsyohfzuknpxzt"
  ,"agirmcjvwhedbsyoqfznknpxgt"
  ,"agiricjvlhedxqyoqfzuknpxwt"
  ,"agirmcjvlhzdbjyoqfzukapxwt"
  ,"agirmcgvlhedbsyoqfzuknaowt"
  ,"agidmcjvlhedbsyoqayuknpxwt"
  ,"agirmcjvlhedisnoqfzuknpxnt"
  ,"wkjrmcjvlhedbsyoqfzuknpxwt"
  ,"agirmcjvlhedbuyojfzukxpxwt"
  ,"agkrmcjvlhedbsybqfzurnpxwt"
  ,"agirmcjvghedbsyoqfzuknexwj"
  ,"agirmcjvnhedbsyoqfzuznpxit"
  ,"agirmcjvlbedbsyoqfiukwpxwt"
  ,"agirlctvlheabsyoqfzuknpxwt"
  ,"agirmcjzzhedbsyoqfzcknpxwt"
  ,"akirmcjvlnedbsyoqfzlknpxwt"
  ,"agirmdjvlhedpsyoqfzuknpjwt"
  ,"agiyjcuvlhedbsyoqfzuknpxwt"
  ,"agirmcbvltedysyoqfzuknpxwt"
  ,"agirmcjvlhedfdyoqfzubnpxwt"
  ,"agidmcjvlhedesfoqfzuknpxwt"
  ,"aeirmcjvlhedqsyoqfxuknpxwt"
  ,"agifmcjvlhedbsyoqfquknptwt"
  ,"agidmcjvlhedbsyfqfzuknpxwb"
  ,"agirvcjvlhedbsroqfzuknjxwt"
  ,"agirmcqvlhddbsyoqfzuknpxwj"
  ,"agirmcjvlhmdqsyoqizuknpxwt"
  ,"atirmcjvltedbsyoqfzuknpxwz"
  ,"agirxnjvlhedbsyoqfzuknpxkt"
  ,"agihmcjvlhedbsyoqfzukepxqt"
  ,"agirmcjvlhedbsmoqzsuknpxwt"
  ,"agirycjvlhedbuyoqfwuknpxwt"
  ,"agirmcjvlhedbsyoqfzfkrfxwt"
  ,"agirzcjvlhedbsyoqfhuknpxnt"
  ,"agigmcjvlhedbsqnqfzuknpxwt"
  ,"agirmgzvlhedbsyoqfzuonpxwt"
  ,"agirmcjvqhedbqyoqfzukqpxwt"
  ,"anarmcjvlhedbsyocfzuknpxwt"
  ,"agirmcjuihedbshoqfzuknpxwt"
  ,"agirdckvlhedbsyoqfzxknpxwt"
  ,"ugirmujvlhwdbsyoqfzuknpxwt"
  ,"mgirmcjvlheobsyovfzuknpxwt"
  ,"agirmcjvghedbsyoqfzufxpxwt"
  ,"agirmcjvlhedbsyoinzuknuxwt"
  ,"agirmzjvlhbdbsyoqfzlknpxwt"
  ,"agivmcjvlhedbsconfzuknpxwt"
  ,"agirmwfvlhedtsyoqfzuknpxwt"
  ,"agirmcjvlhedbbyoqrzukncxwt"
  ,"agirmcjvlhelbsyoqfzupnlxwt"
  ,"agirmmjvluedqsyoqfzuknpxwt"
  ,"agjrmcjvlhedbsyaqfcuknpxwt"
  ,"agiwmcjvlhedbsyoqzzuknpswt"
  ,"agirxcjvlhedbsyoqfyvknpxwt"
  ,"agirmljvlhedbsyoqkzuknpxjt"
  ,"agirmcjvchedbsyoqfzmknyxwt"
  ,"agirmcjvlhedbsyovfzuynpxwl"
  ,"agtrmcjvlhedysyoqfzuknexwt"
  ,"agirmcjvmhedbslonfzuknpxwt"
  ,"agirmcjfshedbsyoqfziknpxwt"
  ,"agirmcjvlhedbsygqfzkknpbwt"
  ,"agyrmcivlhedbsyovfzuknpxwt"
  ,"agirmcjvghedbsyoqjzuknkxwt"
  ,"agirmcjvlhedqsyoqfzukspxmt"
  ,"ayirmcjvhhedbsyomfzuknpxwt"
  ,"agirmcjvlnembsypqfzuknpxwt"
  ,"agirmcjqlhedbsyuvfzuknpxwt"
  ,"agirmcjvlhembsybqfzuknpxwa"
  ,"agirjcfvlhedbsyoqfuuknpxwt"
  ,"agirmcjvohedbsyowfzuknxxwt"
  ,"agirmcjvlhedroyoqfzukncxwt"
  ,"agrrmijvlhedbsyoqfnuknpxwt"
  ,"agirmjjvlhsdbsyoqfzumnpxwt"
  ,"agirrcjvnhedbsyoqfzuktpxwt"
  ,"agirmcjvlzedjsyoqfzuknpdwt"
  ,"agirmkjvlhedbsyoqfzxinpxwt"
  ,"agirmcjvlhedbzyojfzuknpvwt"
  ,"arirmcjvlheddsyoqfzuknrxwt"
  ,"agirmcjvlhedbsyoqhzuanpxmt"
  ,"agirmcjvluedbsyoqozuknwxwt"
  ,"afirmcjwlhedxsyoqfzuknpxwt"
  ,"agirmcjvlhefbsyoqfkuinpxwt"
  ,"agirycjvltedbsypqfzuknpxwt"
  ,"agirmrxvlhedbsyoqfzeknpxwt"
  ,"agfrmcqvlhedbsyoqxzuknpxwt"
  ,"agormcjvuhexbsyoqfzuknpxwt"
  ,"agyrmcjvehddbsyoqfzuknpxwt"
  ,"agirmcjvlheqbsynqfzgknpxwt"
  ,"agirmcjvlhedbsloufwuknpxwt"
  ,"tgirmcjvlwedbsyoqfzuknpqwt"
  ,"agirmcjvlhesbzyogfzuknpxwt"
  ,"agitmdjvlhedpsyoqfzuknpjwt"
  ,"bgirmejvlhtdbsyoqfzuknpxwt"
  ,"aginmcjvlhedzsyoqfzuknoxwt"
  ,"agvrzcjvlhedbsuoqfzuknpxwt"
  ,"agormcjvlhedbsyoqfzuknpodt"
  ,"agirmcevlhedbgyojfzuknpxwt"
  ,"agirmcjblhedboytqfzuknpxwt"
  ,"qgibmcjvlhedbsyoqfzuknbxwt"
  ,"agirmcjvlhedbsyoafzutnnxwt"
  ,"agiamcjvchkdbsyoqfzuknpxwt"
  ,"agirmcjvehedblyoqwzuknpxwt"
  ,"agirmcpvlhwdbsyoafzuknpxwt"
  ,"agirmcjvlhtdbsyoqfzumnpxtt"
  ,"agirmcjalhegtsyoqfzuknpxwt"
  ,"agirdijvlhedbsyoqfzutnpxwt"
  ,"agirmckvlhgdbsyovfzuknpxwt"
  ,"qgmrmcjvlkedbsyoqfzuknpxwt"
  ,"agirjcjvlhodbsyoqfzuanpxwt"
  ,"ajirmcjvlhedbpyoqftuknpxwt"
  ,"cgirmcjvlhedbsyoqfiuonpxwt"
  ,"ayirmcjvlhedbsyaqfzuknwxwt"
  ,"agirmcjvlhedbdyoqbzwknpxwt"]
